const config = {
	tilemap: {
		tileWidth: 200,
		tileHeight: 200,
		gridSize: 64,
	},
	assetKeys: {
		tileset: "tileset",
		grass: "grass",
		ice: "ice",
		rock: "rock",
		sand: "sand",
		water: "water",
		frog: "frog",
		arrow: "arrow",
		item: "item",
		monster: "monster",
		"frog blue": "frog blue",
		"frog green": "frog green",
		"frog teal": "frog teal",
		"frog pink": "frog pink",
		"blue potion": "blue potion",
		"red potion": "red potion",
		"wooden sword": "wooden sword",
		"iron sword": "iron sword",
		"diamond sword": "diamond sword",
		treasure: "treasure",
		imp: "imp",
		"heavy enemy": "heavy enemy",
		bat: "bat",
		dragon: "dragon",
		"prickly bush": "prickly bush",
		sounds: {
			background: "background",
			click: "click",
			impact: "impact",
			powerup: "powerup",
			ready: "ready",
			success: "success",
		},
	},
	animationDuration: 300,
};

export default config;
