[package]
name = "phantom-benchs"
version = "0.1.0"
edition = "2021"

[dependencies]
# phantom-zone-evaluator = { git = "https://github.com/gausslabs/phantom-zone", rev = "5232e55bfa811487438c34f745cf830b9b1f22d9", features = [
#     "serde",
#     "dev",
# ] }
# phantom-zone-evaluator = { git = "https://github.com/gausslabs/phantom-zone", branch = "rewrite", features = [
#     "serde",
#     "dev",
# ] }
phantom-zone-evaluator = { git = "https://github.com/gausslabs/phantom-zone", rev = "55f650debffa5a23b9fd3acc58e08f509f2dd650", features = ["serde", "dev"] }

rand = { version = "0.8.5", default-features = false, features = ["std_rng"] }
rayon = "1.10.0"
itertools = "0.13.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
