[package]
name = "phantom-client"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rocket = { version = "0.5.1", features = ["json"] }
rocket_cors = "0.6.0"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = "1.40.0"
tracing = "0.1.40"
phantom = { path = "../phantom" }
