[package]
name = "worker"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
rocket_cors = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
tokio = "1.40.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
itertools = "0.13.0"
phantom = { path = "../phantom" }
phantom-benchs = { path = "../circuits" }
server = { path = "../server" }
bincode = "1.3.3"
